framework:
    messenger:
        serializer:
            default_serializer: messenger.transport.symfony_serializer
            symfony_serializer:
                format: json
                context:
                    json_encode_options: !php/const JSON_PRESERVE_ZERO_FRACTION

        transports:
            openweathermap-compute:
                dsn: "vdm+local://%kernel.project_dir%/local/openweathermap-compute.json?encodeBody=json"
                retry_strategy:
                    max_retries: 0

            openweathermap-send-to-store:
                dsn: "vdm+local://%kernel.project_dir%/local/openweathermap-compute-output.json?encodeBody=json"
                retry_strategy:
                    max_retries: 0

        routing:
            App\Message\OpenWeatherMapStoreMessage: openweathermap-send-to-store
