framework:
    messenger:
        serializer:
            default_serializer: messenger.transport.symfony_serializer
            symfony_serializer:
                format: json
                context:
                    json_encode_options: !php/const JSON_PRESERVE_ZERO_FRACTION

        transports:
            openweathermap-store:
                dsn: "vdm+local://%kernel.project_dir%/local/openweathermap-store.json?encodeBody=json"
                retry_strategy:
                    max_retries: 0

            openweathermap-send-to-db:
                dsn: "vdm+local://%kernel.project_dir%/local/openweathermap-store-output.json?encodeBody=json"
                retry_strategy:
                    max_retries: 0

        routing:
            App\Message\OpenWeatherMapPersistMessage: openweathermap-send-to-db
