framework:
    messenger:
        serializer:
            default_serializer: messenger.transport.symfony_serializer
            symfony_serializer:
                format: json
                context:
                    json_encode_options: !php/const JSON_PRESERVE_ZERO_FRACTION

        transports:
            openweathermap-compute:
                dsn: "%env(RABBITMQ_DSN)%"
                retry_strategy:
                    max_retries: 0
                options:
                    auto_setup: "true"
                    heartbeat: "60"
                    read_timeout: "60"
                    write_timeout: "60"
                    prefetch_count: "1"
                    queues:
                        "openweathermap_hourly": ~

            openweathermap-send-to-store:
                dsn: "%env(RABBITMQ_DSN)%"
                retry_strategy:
                    max_retries: 0
                options:
                    auto_setup: "true"
                    heartbeat: "60"
                    read_timeout: "60"
                    write_timeout: "60"
                    prefetch_count: "1"
                    queues:
                        "openweathermap_hourly_formated": ~
                    exchange:
                        name: "openweathermap_hourly_formated"

        routing:
            App\Message\OpenWeatherMapStoreMessage: openweathermap-send-to-store
